### ISSUE TITLE
Speed of request processing.

### ISSUE THREAD

**Issue by smthngslv** [eora-ai/inferoxy#19]
I have a problem with very slow requests processing.  

Ten parallel (or sequential) requests with only one image as input are processing for ±8 minutes, while one single (first) request takes ±10 seconds to complete. 

In the logs it seems like inferoxy waits for something before process the image.

There is a log:
[log.log](https://github.com/eora-ai/inferoxy/files/6777041/log.log)

The image:
![test](https://user-images.githubusercontent.com/38153388/124757906-be5e2100-df36-11eb-9d78-b9c51b384bdb.jpg)

The model can be dowloaded from docker hub:
`docker pull smthngslv/clip_vit-b32_no_proj:latest`

Code, image, log.
[Archive.zip](https://github.com/eora-ai/inferoxy/files/6777220/Archive.zip)

Also, does the setting exists , that allow to do not shutdown the container between requests (I mean, run sequential requests on the same container)?

**Comment by wselfjes** [comment]
Inferoxy waits for a container creation. 

Could you also send a `models.yaml` file, or code snippet where you define a model.
Also, I need some information about a host system: RAM, CPU and GPUs.
Also if you, somehow, changed the inferoxy config, please send it too.

You can set `LOGGING_LEVEL=DEBUG` in environment variables to obtain more information about the system.

**Comment by wselfjes** [comment]
To speed up the inference, you could set `model.stateless = True`.

Inferoxy tends to stop an old stateful container and starting a new one after it finishes processing a batch. This behaviour could be considered as a bug. I will inspect the problem after @smthngslv your report with `DEBUG=True`.

**Comment by smthngslv** [comment]
Here  are [model.yaml, inferoxy.log and docker-compose.yml](https://gist.github.com/smthngslv/7200d2af0bc762eeb198c0b6d7b13d2b)

Firstly I've sent one image and then five images in parallel. Also I've tried set batch size to 16, it didn't help. Other model has the same behaviour. In both variants (and previous times too) I used `stateless=True`.

System config:
RAM: 32gb
CPU: 8 core  Xeon(R) Platinum 8259CL CPU @ 2.50GHz
GPU: Nvidia Tesla T4 16gb

**Comment by wselfjes** [comment]
Thank you!
I will inspect the logs tonight.

**Comment by wselfjes** [comment]
I noticed that ModelObject for the received batch is built with `stateless=False`. If you want to use the model in the stateless mode you should pass `stateless: True` in the `parameters` field. 

The problem with the performance appears because inferoxy can not remove old stateful container in `TASK_MANAGER_STATEFUL_CHECKER_KEEP_MODEL`(30 by default)  seconds from the last sent batch to the model.

There are two solutions:
1. Set stateless=True in parameters field of the request
2. Set `TASK_MANAGER_STATEFUL_CHECKER_KEEP_MODEL` with low value, for example 1 second

**Comment by wselfjes** [comment]
I divided this issue in two: #20 #21
